<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autodesk.Authentication" Version="2.0.1" />
    <PackageReference Include="Autodesk.DataManagement" Version="2.1.3" />
    <PackageReference Include="Autodesk.Oss" Version="2.3.3" />
  </ItemGroup>

</Project>
